//Localhost ###  
GET http://localhost:3000/contacts
GET http://localhost:3000/contacts/696c68bfdd048f0e14ee379b
GET http://localhost:3000/contacts/696c68f4dd048f0e14ee379c
GET http://localhost:3000/contacts/696c6911dd048f0e14ee379d

//Productions Deploy ### 
GET https://cse341.onrender.com/contacts
GET https://cse341.onrender.com/contacts/696c68bfdd048f0e14ee379b
GET https://cse341.onrender.com/contacts/696c68f4dd048f0e14ee379c
GET https://cse341.onrender.com/contacts/696c6911dd048f0e14ee379d